### ISSUE TITLE
Feature: Debug Mode

### ISSUE THREAD

**Issue by kreck** [aws/aws-sdk-mobile-analytics-js#6]
Awesome Product, i'm excited to see it grow further (especially the dashboard on AWS).

On the JS SDK: it would be perfect to have an optional "Debug Mode" that logs Event submissions to the Console. Currently it's really hard to determine if it actually "works" when i'm running outside the browser on a mobile device WebView (Cordova).

Cheers

**Comment by cheruvian** [comment]
Hi kreck, 

You can pass a logger object as part of the [AMA.Client.Options object](https://aws.github.io/aws-sdk-mobile-analytics-js/doc/AMA.Client.html#Options).

It accepts a [logger object](https://aws.github.io/aws-sdk-mobile-analytics-js/doc/AMA.Client.html#Logger) designed in such a way that you can just pass it console (since console has .log, .error, .info, .debug).  

If you are developing on Cordova/Phonegap you can use the [PhoneGap Developer App](http://app.phonegap.com/) which will proxy the console logs from a mobile device back to your desktop.

Thanks,
RIL@AWS
